Add CI workflow
cloudlab-cmu/cloudcompchem pull request #31
Opened 2024-05-01 16:14 UTC by Leticia-maria

TODO
- add more python versions
- run tests on repo
- should I test across multiple OS setups? @tommyh-ECL

2024-05-01 16:23 UTC, Leticia-maria commented
Related to #31

2024-05-15 18:14 UTC, tommyh-ECL requested changes
minor fixes

2024-05-15 18:14 UTC, tommyh-ECL commented on .github/workflows/CI.yml
> +        python-version: 3.7
update python version

2024-05-15 18:14 UTC, tommyh-ECL commented on .github/workflows/CI.yml
> +    - name: Set up python 3.7
update python version

2024-05-15 18:14 UTC, tommyh-ECL commented on .github/workflows/CI.yml
> +        python -m unittest -v
we use `pytest` not `unittest` for this package

2024-05-15 18:14 UTC, tommyh-ECL commented on .github/workflows/CI.yml
> +      uses: actions/upload-artifact@v2
where does this get uploaded to? will this upload the package to `pypi`? Ideally, we'd like to conditionally upload the package to pypi upon version changes in the `setup.py` file

2024-06-20 16:27 UTC, Leticia-maria commented
I think it is ready to merge @tommyh-ECL

2024-06-20 16:37 UTC, tommyh-ECL approved these changes

2024-11-01 17:20 UTC, merged