Modify `run_dft_opt` function to return hessian and frequencies
cloudlab-cmu/cloudcompchem pull request #40
Opened 2024-11-01 17:30 UTC by Leticia-maria

TODO:

- Add a function that corrects imaginary (negative frequencies)
- Add tests

@bruno-ecl As of now, I have added the functionality to the `run_dft_opt` function, would we rather have a separate function instead or do you think the way it is right now works?

I added to the `run_dft_opt` because the good practice in computational chemistry is to proceed with frequency calculations after you optimize the geometry, so I thought it would be nice to have it already embedded with geometry optimization, which does mean that I could not have it as a separate function tho. 😄

2024-11-01 17:32 UTC, Leticia-maria commented
This PR addresses #21 and #23

2024-11-01 18:08 UTC, Leticia-maria commented
- As per @yiwenwang47 said, frequency calculations will be optional and requested by the user. (I will just add it into a separate function)

2025-02-11 18:34 UTC, bruno-ecl requested changes

2025-02-11 18:34 UTC, bruno-ecl commented on cloudcompchem/opt.py
> +from pyscf.hessian import Hessian
I'm getting an import error from this line. Shouldn't it be

```
from pyscf.hessian.rhf import Hessian
```
?

2025-02-11 18:34 UTC, bruno-ecl commented on cloudcompchem/opt.py
> +    frequencies = hessian_calculator.frequencies()
This line is also triggering an exception:

> AttributeError: 'Hessian' object has no attribute 'frequencies'

2025-02-11 18:34 UTC, bruno-ecl commented on cloudcompchem/opt.py
> +    )
The `StructureRelaxationResponse` doesn't have these two properties:

<img width="580" alt="image" src="https://github.com/user-attachments/assets/f6142eb3-bec5-4b9a-908a-690a1d00c6fd" />

2025-03-14 18:33 UTC, bruno-ecl approved these changes

2025-03-14 18:33 UTC, merged